apiVersion: v1
kind: Service
metadata:
  name: kai-test-svc
  labels:
    app: kai-test
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: kai-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kai-test
  labels:
    app: kai-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kai-test
  template:
    metadata:
      labels:
        app: kai-test
    spec:
      containers:
        - name: kai-test
          image: whoaremine/kai_test:latest
          ports:
            - containerPort: 8081